### PR TITLE
Faster LENS calculation using FastNS

### PR DESCRIPTION
**Pull request by tulga-rdn**
<oops, posted the previous pull request through my throwaway account, sorry>

Hello,

I'm an undergraduate researcher at Prof. Taras Pogorelov's lab at UIUC. I am using LENS for my research, and I found a faster way of calculating LENS parameters, so I thought I would share it. I didn't find any issues and the results were identical to your original code, can you please check as well? Thanks!

### CODE REVIEW

**Comment by andrewtarzia** [comment]
Hey @tulga-rdn , we will have a look t this soon, thank you for your interest and support!

**Comment by andrewtarzia** [comment]
Hey @tulga-rdn, this looks great, and like a simple 1:1 replacement. Thank you!

If you want me to merge this into the main, we will need to fix all the failed checks.

* You can ignore the first `ruff` check, because that is something we need to change that has nothing to do with the changes you have made.
* For the mypy and ruff-format checks, to reproduce those locally, you can do `just check` in the terminal at the repositories home if you have `just` installed. Otherwise you can open the `justfile` and find out the `mypy` and `ruff-format` commands that are used and run those.
*  For the pytests, there seems to be an issue with cut-offs that FastNS is stricter about than before? Feel free to modify the conftest.py to handle this issue.

**Comment by tulga-rdn** [comment]
Oops, it seems to still have errors. Will fix them soon

**Comment by SimoneMartino98** [comment]
Hey @tulga-rdn, thanks for your interest, I took a look at your last commit and it seems that there is an issue with the argument `_prepare_box` which, if I understood correctly, is a private argument that read the box dimensions in order to choose the biggest cutoff radius possible. I cannot find the part of code for this argument, can you include that code so we can review it?

**Comment by andrewtarzia** [comment]
Hey @tulga-rdn  and @SimoneMartino98. I will close this for now, but feel free to reopen if either of you make progress.

Thank you

**Pull request closed without merging**
